export default [
  [
    { "The weather is fine today": "Il fait beau aujourd'hui" },
    { "I'm not rich": "Je ne suis pas riche" },
    { "This bag is heavy": "Ce sac est lourd" },
    { "These bags are heavy": "Ces sacs sont lourds" },
    { "Look, there's my friend": "Regarde, voilà mon ami" },
    { "My brother and I are good tennis players": "Mon frère et moi sommes de bons joueurs de tennis" },
    { "His mother's at home. He's at school": "Sa mère est à la maison. Il est à l'école" },
    { "Her children are at school": "Ses enfants sont à l'école" },
    { "I'm a taxi driver": "Je suis chauffeur de taxi" },
    { "My sister's a nurse": "Ma sœur est infirmière" },
  ],
  [
    { "He's sick. He's in bed": "Il est malade. Il est au lit" },
    { "I'm not hungry, but I'm thirsty": "Je n'ai pas faim, mais j'ai soif" },
    { "He's a very old man. He's ninety-eight (98) years old": "Il est un très vieil homme. Il a quatre-vingt-dix-huit ans" },
    { "These chairs aren't beautiful, but they're comfortable": "Ces chaises ne sont pas très belles, mais elles sont confortables" },
    { "The weather's warm and sunny today.": "Il fait chaud et ensoleillé aujourd'hui" },
    { "You're late. — No, I'm not! I'm early.": "Tu es en retard. — Non, je ne le suis pas! Je suis en avance" },
    { "She isn't home. She's at work.": "Elle n'est pas à la maison. Elle est au travail" },
    { "Here's your coat.": "Voici ton manteau" },
    { "What's your name?": "Comment t'appelles-tu?" },
    { "My name's Alan.": "Je m'appelle Alan" },
  ],
  [
    { "Where are you from?": "D'où viens-tu?" },
    { "I'm from New York.": "Je viens de New York" },
    { "How old are you?": "Quel âge as-tu?" },
    { "I'm twenty (20) years old.": "J'ai vingt ans" },
    { "What's your job?": "Quel est ton métier?" },
    { "I'm a teacher. (with femmetive)": "Je suis enseignant (enseignante)" },
    { "What's your favorite color?": "Quelle est ta couleur préférée?" },
    { "My favorite color is blue.": "Ma couleur préférée est le bleu" },
    { "What are you interested in?": "À quoi t'intéresses-tu?" },
    { "I'm interested in music.": "Je m'intéresse à la musique" },
  ],
  [
    { "It's hot today": "Il fait chaud aujourd'hui" },
    { "It isn't hot today.": "Il ne fait pas chaud aujourd'hui" },
    { "It's windy today.": "C'est venteux aujourd'hui" },
    { "It isn't windy today": "Ce n'est pas venteux aujourd'hui" },
    { "My hands are cold": "Mes mains sont froides" },
    { "Brazil is a very big country": "Le Brésil est un très grand pays" },
    { "Diamonds are not cheap": "Les diamants ne sont pas bon marché" },
    { "Toronto isn't in the United States.": "Toronto n'est pas aux États-Unis" },
    { "I'm tired (with femmetive)": "Je suis fatigué (fatiguée)" },
    { "I'm not tired (with femmetive)": "Je ne suis pas fatigué (fatiguée)" },
  ],
  [
    { "I'm hungry.": "J'ai faim" },
    { "I'm not hungry.": "Je n'ai pas faim" },
    { "He's a good swimmer": "Il est bon nageur" },
    { "I'm not interested in politics": "Je ne m'intéresse pas à la politique" },
    { "What's your name?": "Comment t'appelles-tu?" },
    { "My name's Amanda.": "Je m'appelle Amanda" },
    { "Are you married? (with femmenitive)": "Es-tu marié (mariée)?" },
    { "No, I'm single.": "Non, je suis célibataire" },
    { "How old are you?": "Quel âge as-tu?" },
    { "I'm twenty-five (25).": "J'ai vingt-cinq ans" },
  ],
  [
    { "Are you a student?": "Es-tu étudiant (étudiante)?" },
    { "Yes, I am [a student].": "Oui, je le suis" },
    { "Am I late?": "Suis-je en retard?" },
    { "No, you're on time.": "Non, tu es à l'heure" },
    { "Is your mother at home?": "Ta mère est-elle à la maison?" },
    { "No, she's out.": "Non, elle est à l'extérieur" },
    { "Are your parents at home?": "Tes parents sont-ils à la maison?" },
    { "No, they're out.": "Non, ils sont à l'extérieur" },
    { "Is it cold in your room?": "Fait-il froid dans ta chambre?" },
    { "Yes, a little.": "Oui, un peu" },
  ],
  [
    { "Your shoes are nice. Are they new?": "Tes chaussures sont jolies. Sont-elles neuves?" },
    { "Yes, they are.": "Oui, elles le sont" },
    { "Where's your mother? Is she at home?": "Où est ta mère? Est-elle à la maison?" },
    { "Where are you from?": "D'où viens-tu?" },
    { "I'm from Canada.": "Je viens du Canada" },
    { "What color is your car?": "De quelle couleur est ta voiture?" },
    { "It's red.": "Elle est rouge" },
    { "How old is Hassan?": "Quel âge a Hassan?" },
    { "He's twenty-four (24)": "Il a vingt-quatre ans" },
    { "How are your parents?": "Comment vont tes parents?" },
  ],
  [
    { "They're doing fine.": "Ils vont bien" },
    { "These postcards are nice. How much are they?": "Ces cartes postales sont jolies. Combien sont-elles?" },
    { "They're a euro": "Elles sont un euro" },
    { "This hotel isn't very good. Why is it so expensive?": "Cet hôtel n'est pas très bon. Pourquoi est-il si cher?" },
    { "What's your phone number?": "Quel est ton numéro de téléphone?" },
    { "Who's that man?": "Qui est cet homme?" },
    { "He's the boss.": "C'est le patron" },
    { "Where's your friend?": "Où est ton amie?" },
    { "She's in the bathroom": "Elle est à la salle de bain" },
    { "How's your father?": "Comment va ton père?" },
  ],
  [
    { "He's doing great": "Il va très bien" },
    { "Are you tired?": "Es-tu fatigué (fatiguée)?" },
    { "Yes, I am": "Oui, je le suis" },
    { "Are you hungry?": "As-tu faim?" },
    { "No, but I'm thirsty": "Non, mais j'ai soif" },
    { "Is your friend Chinese?": "Ton ami est-il Chinois?" },
    { "Yes, he is": "Oui, il l'est" },
    { "Are these your keys?": "Ce sont tes clés?" },
    { "Yes, they are [mine]": "Oui, ce sont les miennes" },
    { "That's my seat": "C'est mon siège" },
  ],
  [
    { "No, it isn't [yours].": "Non, ce ne l'est pas" },
    { "Where's the camera?": "Où est la caméra?" },
    { "It's in your bag.": "Elle est dans ton sac." },
    { "Is your car blue?": "Ta voiture est-elle bleue?" },
    { "No, it's black.": "Non, elle est noire." },
    { "Is Lisa from Toronto?": "Lisa est-elle de Toronto?" },
    { "No, she's American.": "Non, elle est Américaine." },
    { "Am I late?": "Suis-je en retard?" },
    { "Yes, you are [late].": "Oui, tu l'es." },
    { "Where's Layla from?": "D'où vient Layla?" },
  ],
  [
    { "She's from London.": "Elle vient de Londres" },
    { "What color is your bag?": "De quelle couleur est ton sac?" },
    { "It's black.": "Il est noir" },
    { "Are you hungry?": "As-tu faim?" },
    { "No, I'm not [hungry].": "Non, je n'ai pas faim." },
    { "How's John?": "Comment va John?" },
    { "He's fine.": "Il va bien." },
    { "Who's that woman?": "Qui est cette femme?" },
    { "She's my sisterey": "C'est ma sœur." },
    { "Is your mother at home?": "Ta mère est-elle à la maison?" },
  ],
  [
    { "How are your parents?": "Comment vont tes parents?" },
    { "Is your job interesting?": "Ton travail est-il intéressant?" },
    { "Are the stores open today?": "Les magasins sont-ils ouverts aujourd'hui?" },
    { "Where are you from?": "D'où viens-tu?" },
    { "Are you interested in sports?": "T'intéresses-tu au sport?" },
    { "Is the post office near here?": "Le bureau de poste est-il près d'ici?" },
    { "Are your children at school?": "Tes enfants sont-ils à l'école?" },
    { "Why are you late?": "Pourquoi es-tu en retard?" },
    { "How are your children?": "Comment vont tes enfants?" },
    { "They're fine.": "Ils vont bien." },
  ],
  [
    { "Where's the bus stop?": "Où est l'arrêt de bus?" },
    { "At the stoplight.": "Au feu de circulation." },
    { "How old are your children?": "Quel âge ont tes enfants?" },
    { "Five (5), seven (7), and ten (10).": "Cinq, sept et dix ans." },
    { "How much are these oranges?": "Combien coûtent ces oranges?" },
    { "They're 2.3 Euros a kilo.": "Deux euros trente le kilo." },
    { "What's your favorite sport?": "Quel est ton sport favori?" },
    { "My favorite sport is skiing": "Mon sport favori est le ski." },
    { "Who's the man in this photo?": "Qui est l'homme sur cette photo?" },
    { "That's my father.": "C'est mon père" },
  ],
  [
    { "What color are your new shoes?": "De quelle couleur sont tes nouvelles chaussures?" },
    { "They're black.": "Elles sont noires." },
    { "What's your name?": "Comment t'appelles-tu?" },
    { "I'm Brian": "Je m'appelle Brian" },
    { "Are you Australian?": "Es-tu Australien?" },
    { "No, I'm Canadian.": "Non, je suis Canadien" },
    { "How old are you?": "Quel âge as-tu?" },
    { "I'm thirty-three.": "J'ai trente-trois ans." },
    { "Are you a teacher?": "Es-tu enseignant?" },
    { "No, I'm a doctor": "Non, je suis médecin." },
  ],
  [
    { "Are you married? (f)": "Es-tu marié (mariée)?" },
    { "Yes, I am [married].": "Oui, je le suis" },
    { "Is your wife a doctor?": "Ta femme est-elle médecin?" },
    { "No, she's a teacher.": "Non, elle est enseignante." },
    { "Where is she from?": "D'où vient-elle?" },
    { "She's from Mexico.": "Elle vient du Mexique" },
    { "What's her name?": "Quel est son nom?" },
    { "Her name is Barbara.": "Elle s'appelle Barbara" },
    { "How old is she?": "Quel âge a-t-elle?" },
    { "She's twenty-six (26).": "Elle a vingt-six ans." },
  ],
  [
    { "Are you married? - No, I'm not.": "Es-tu marié? — Non, je ne le suis pas." },
    { "Are you thirsty? — Yes, I am.": "As-tu soif? - Oui, j'ai soif" },
    { "Is it cold today? — No, it isn't.": "Fait-il froid aujourd'hui? — Non, il ne fait pas froid." },
    { "Are your hands cold? — No, they aren't": "Tes mains sont-elles froides? — Non, elles ne le sont pas." },
    { "Is it dark now? — Yes, it is.": "Fait-il noir maintenant? — Oui, il fait noir" },
    { "Are you a teacher? — Yes, I am.": "Es-tu enseignant? — Oui, je le suis" },
    { "I'm working. I'm not watching TV.": "Je suis en train de travailler. Je ne suis pas en train de regarder la télé." },
    { "Barbara is reading a newspaper.": "Barbara lit le journal." },
    { "She isn't eating.": "Elle n'est pas en train de manger." },
    { "The phone is ringing.": "Le téléphone sonne." },
  ],
  [
    { "We're having dinner.": "Nous dînons" },
    { "You're not listening to me.": "Tu ne m'écoutes pas." },
    { "The children are doing their homework": "Les enfants sont en train de faire leurs devoirs." },
    { "Please be quiet. I'm working.": "Silence, s'il te plaît. Je travaille." },
    { "The weather's nice. It's not raining.": "Il fait beau. Il ne pleut pas." },
    { "Where are the children? — They're playing in the park.": "Où sont les enfants? — Ils jouent au parc." },
    { "We're having dinner now. Can I call you later?": "Nous sommes en train de dîner. Je peux te rappeler plus tard?" },
    { "I'm not watching TV.": "Je ne regarde pas la télé." },
    { "She's eating an apple.": "Elle mange une pomme" },
    { "He's waiting for a bus.": "Il attend un bus" },
  ],
  [
    { "They're playing football.": "Ils jouent au foot." },
    { "He's lying on the floor.": "Il est couché sur le sol." },
    { "We're eating breakfast.": "Nous prenons le petit déjeuner." },
    { "She's sitting on the table.": "Elle est assise sur la table." },
    { "He's in the kitchen. He's cooking": "Il est dans la cuisine. Il cuisine." },
    { "You stepped on my foot. — I'm sorry.": "Tu m'as marché sur le pied. — Je suis désolé" },
    { "Somebody is swimming in the river.": "Quelqu'un nage dans la rivière." },
    { "We're here on vacation. We're staying at a hotel on the beach.": "Nous sommes en vacances. Nous séjournons dans un hôtel sur la plage." },
    { "Where's Tara? — She's taking a shower.": "Où est Tara? — Elle prend une douche." },
    { "They're building a new hotel downtown.": "Ils construisent un nouvel hôtel au centre-ville" },
  ],
  [
    { "I'm leaving now, goodbye.": "J'y vais maintenant, salut." },
    { "She isn't having dinner.": "Elle n'est pas en train de dîner." },
    { "She's watching TV.": "Elle regarde la télé." },
    { "She's sitting on the floor.": "Elle est assise sur le sol." },
    { "She's reading a book.": "Elle lit un livre." },
    { "He's not playing the piano.": "Il n'est pas en train de jouer du piano." },
    { "He's laughing.": "Il rit." },
    { "He's wearing a hat.": "Il porte un chapeau" },
    { "He's not writing a letter.": "Il n'est pas en train d'écrire une lettre." },
    { "I'm not washing my hair": "Je ne suis pas en train de me laver les cheveux." },
  ],
  [
    { "It isn't snowing.": "Il ne neige pas." },
    { "I'm sitting on a chair.": "Je suis assis sur une chaise." },
    { "I'm not eating.": "Je ne suis pas en train de manger." },
    { "It's raining.": "Il pleut" },
    { "I'm not studying english.": "Je ne suis pas en train d'étudier l'anglais." },
    { "I'm listening to music.": "J'écoute de la musique." },
    { "The sun isn't shining.": "Le soleil ne brille pas." },
    { "I'm wearing my shoes.": "Je porte mes chaussures." },
    { "I'm not reading the newspaper.": "Je ne suis pas en train de lire le journal." },
    { "Are you feeling okay?": "Te sens-tu bien?" },
  ],
  [
    { "Yes, I'm fine.": "Oui, je me sens bien." },
    { "Is it raining?": "Est-ce qu'il pleut?" },
    { "Yes, take an umbrella.": "Oui, prends un parapluie." },
    { "Why are you wearing a coat?": "Pourquoi portes-tu un manteau?" },
    { "It's not cold": "Il ne fait pas froid." },
    { "What's he doing?": "Que fait-il?" },
    { "He's reading the newspaper.": "Il lit le journal." },
    { "What are the children doing?": "Que font les enfants?" },
    { "They're watching TV.": "Ils regardent la télé." },
    { "Where's she going?": "Où va-t-elle?" },
  ],
  [
    { "Who are you waiting for?": "Qui attends-tu?" },
    { "Are you waiting for John?": "Attends-tu John?" },
    { "Are you leaving now?": "Tu pars maintenant?" },
    { "Yes, I am [leaving now]": "Oui, je pars maintenant." },
    { "Is Chris working today?": "Est-ce que Chris travaille aujourd'hui?" },
    { "No, he isn't [working].": "Non, il ne travaille pas aujourd'hui." },
    { "Is the sun shining?": "Le soleil brille-t-il?" },
    { "Yes, it is, [the sun is shining].": "Oui, il brille." },
    { "Are your friends staying at a hotel?": "Tes amis séjournent-ils à l'hôtel?" },
    { "No, they're staying with me": "Non, ils séjournent chez moi." },
  ],
  [
    { "Are you watching TV?": "Regardes-tu la télé?" },
    { "No, you can turn it off.": "Non, tu peux l'éteindre." },
    { "Are you leaving now?": "Tu pars maintenant?" },
    { "Yes, see you tomorrow.": "Oui, on se voit demain" },
    { "Is it raining?": "Pleut-il?" },
    { "No, not right now.": "Non, pas maintenant." },
    { "Are you enjoying the movie?": "Le film te plaît?" },
    { "Yes, it's very funny.": "Oui, c'est vraiment drôle." },
    { "Does the clock work?": "L'horloge fonctionne-t-elle?" },
    { "No, it's broken": "Non, elle est cassée" },
  ],
  [
    { "Are you waiting for a bus?": "Tu attends un bus?" },
    { "No, I'm waiting for a taxi.": "Non, j'attends un taxi." },
    { "What are you reading?": "Qu'est-ce que tu lis?" },
    { "Where is she going?": "Où va-t-elle?" },
    { "What are you eating?": "Qu'est-ce que tu manges?" },
    { "Why are you crying?": "Pourquoi pleures-tu?" },
    { "What are they looking at?": "Qu'est-ce qu'ils regardent?" },
    { "Why is he laughing?": "Pourquoi rit-il?" },
    { "Are you listening to me?": "M'écoutes-tu?" },
    { "Where are your friends going?": "Où vont tes amis?" },
  ],
  [
    { "Are your parents watching TV?": "Tes parents regardent-ils la télé?" },
    { "What's Claire cooking?": "Qu'est-ce que Claire cuisine?" },
    { "Why are you looking at me?": "Pourquoi me regardes-tu?" },
    { "Is the bus coming?": "Est-ce que l'autobus arrive?" },
    { "Are you watching TV?": "Regardes-tu la télé?" },
    { "No, I'm not [watching TV].": "Non, je ne la regarde pas." },
    { "Are you wearing a watch?": "Portes-tu une montre?" },
    { "No, I'm not [wearing a watch].": "Non, je n'en porte pas." },
    { "Is he eating something?": "Il est en train de manger quelque chose?" },
    { "No, he isn't [eating].": "Non, il ne mange pas." },
  ],
  [
    { "Is it raining?": "Est-ce qu'il pleut?" },
    { "No, it isn't [raining].": "Non, il ne pleut pas." },
    { "Are you sitting on the floor?": "Es-tu assis sur le sol?" },
    { "Yes, I am [sitting on the floor].": "Oui, je le suis." },
    { "Are you feeling all right?": "Est-ce que tu te sens bien?" },
    { "No, I'm not [feeling all right].": "Non, je ne me sens pas bien." },
    { "They're looking at their books.": "Ils regardent leurs livres." },
    { "They read a lot.": "Ils lisent beaucoup." },
    { "He's eating ice cream.": "Il mange de la glace" },
    { "He likes ice cream.": "Il aime la glace" },
  ],
  [
    { "I work in an office.": "Je travaille dans un bureau." },
    { "My brother works in a bank.": "Mon frère travaille dans une banque" },
    { "She lives in New York.": "Elle vit à New York." },
    { "Her parents live in Chicago": "Ses parents habitent à Chicago." },
    { "It rains a lot in the winter.": "Il pleut beaucoup en hiver." },
    { "Mike has lunch at home every day.": "Mike déjeune à la maison tous les jours." },
    { "I like big cities.": "J'aime les grandes villes." },
    { "Your English is good.": "Ton anglais est bon." },
    { "You speak English very well.": "Tu parles très bien anglais." },
    { "Minoru works very hard.": " Minoru travaille très fort." },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
]