export default [
  [
    { "The weather is fine today": "Il fait beau aujourd'hui" },
    { "I'm not rich": "Je ne suis pas riche" },
    { "This bag is heavy": "Ce sac est lourd" },
    { "These bags are heavy": "Ces sacs sont lourds" },
    { "Look, there's my friend": "Regarde, voilà mon ami" },
    { "My brother and I are good tennis players": "Mon frère et moi sommes de bons joueurs de tennis" },
    { "His mother's at home. He's at school": "Sa mère est à la maison. Il est à l'école" },
    { "Her children are at school": "Ses enfants sont à l'école" },
    { "I'm a taxi driver": "Je suis chauffeur de taxi" },
    { "My sister's a nurse": "Ma sœur est infirmière" },
  ],
  [
    { "He's sick. He's in bed": "Il est malade. Il est au lit" },
    { "I'm not hungry, but I'm thirsty": "Je n'ai pas faim, mais j'ai soif" },
    { "He's a very old man. He's ninety-eight (98) years old": "Il est un très vieil homme. Il a quatre-vingt-dix-huit ans" },
    { "These chairs aren't beautiful, but they're comfortable": "Ces chaises ne sont pas très belles, mais elles sont confortables" },
    { "The weather's warm and sunny today.": "Il fait chaud et ensoleillé aujourd'hui" },
    { "You're late. — No, I'm not! I'm early.": "Tu es en retard. — Non, je ne le suis pas! Je suis en avance" },
    { "She isn't home. She's at work.": "Elle n'est pas à la maison. Elle est au travail" },
    { "Here's your coat.": "Voici ton manteau" },
    { "What's your name?": "Comment t'appelles-tu?" },
    { "My name's Alan.": "Je m'appelle Alan" },
  ],
  [
    { "Where are you from?": "D'où viens-tu?" },
    { "I'm from New York.": "Je viens de New York" },
    { "How old are you?": "Quel âge as-tu?" },
    { "I'm twenty (20) years old.": "J'ai vingt ans" },
    { "What's your job?": "Quel est ton métier?" },
    { "I'm a teacher. (with femmetive)": "Je suis enseignant (enseignante)" },
    { "What's your favorite color?": "Quelle est ta couleur préférée?" },
    { "My favorite color is blue.": "Ma couleur préférée est le bleu" },
    { "What are you interested in?": "À quoi t'intéresses-tu?" },
    { "I'm interested in music.": "Je m'intéresse à la musique" },
  ],
  [
    { "It's hot today": "Il fait chaud aujourd'hui" },
    { "It isn't hot today.": "Il ne fait pas chaud aujourd'hui" },
    { "It's windy today.": "C'est venteux aujourd'hui" },
    { "It isn't windy today": "Ce n'est pas venteux aujourd'hui" },
    { "My hands are cold": "Mes mains sont froides" },
    { "Brazil is a very big country": "Le Brésil est un très grand pays" },
    { "Diamonds are not cheap": "Les diamants ne sont pas bon marché" },
    { "Toronto isn't in the United States.": "Toronto n'est pas aux États-Unis" },
    { "I'm tired (with femmetive)": "Je suis fatigué (fatiguée)" },
    { "I'm not tired (with femmetive)": "Je ne suis pas fatigué (fatiguée)" },
  ],
  [
    { "I'm hungry.": "J'ai faim" },
    { "I'm not hungry.": "Je n'ai pas faim" },
    { "He's a good swimmer": "Il est bon nageur" },
    { "I'm not interested in politics": "Je ne m'intéresse pas à la politique" },
    { "What's your name?": "Comment t'appelles-tu?" },
    { "My name's Amanda.": "Je m'appelle Amanda" },
    { "Are you married? (with femmenitive)": "Es-tu marié (mariée)?" },
    { "No, I'm single.": "Non, je suis célibataire" },
    { "How old are you?": "Quel âge as-tu?" },
    { "I'm twenty-five (25).": "J'ai vingt-cinq ans" },
  ],
  [
    { "Are you a student?": "Es-tu étudiant (étudiante)?" },
    { "Yes, I am [a student].": "Oui, je le suis" },
    { "Am I late?": "Suis-je en retard?" },
    { "No, you're on time.": "Non, tu es à l'heure" },
    { "Is your mother at home?": "Ta mère est-elle à la maison?" },
    { "No, she's out.": "Non, elle est à l'extérieur" },
    { "Are your parents at home?": "Tes parents sont-ils à la maison?" },
    { "No, they're out.": "Non, ils sont à l'extérieur" },
    { "Is it cold in your room?": "Fait-il froid dans ta chambre?" },
    { "Yes, a little.": "Oui, un peu" },
  ],
  [
    { "Your shoes are nice. Are they new?": "Tes chaussures sont jolies. Sont-elles neuves?" },
    { "Yes, they are.": "Oui, elles le sont" },
    { "Where's your mother? Is she at home?": "Où est ta mère? Est-elle à la maison?" },
    { "Where are you from?": "D'où viens-tu?" },
    { "I'm from Canada.": "Je viens du Canada" },
    { "What color is your car?": "De quelle couleur est ta voiture?" },
    { "It's red.": "Elle est rouge" },
    { "How old is Hassan?": "Quel âge a Hassan?" },
    { "He's twenty-four (24)": "Il a vingt-quatre ans" },
    { "How are your parents?": "Comment vont tes parents?" },
  ],
  [
    { "They're doing fine.": "Ils vont bien" },
    { "These postcards are nice. How much are they?": "Ces cartes postales sont jolies. Combien sont-elles?" },
    { "They're a euro": "Elles sont un euro" },
    { "This hotel isn't very good. Why is it so expensive?": "Cet hôtel n'est pas très bon. Pourquoi est-il si cher?" },
    { "What's your phone number?": "Quel est ton numéro de téléphone?" },
    { "Who's that man?": "Qui est cet homme?" },
    { "He's the boss.": "C'est le patron" },
    { "Where's your friend?": "Où est ton amie?" },
    { "She's in the bathroom": "Elle est à la salle de bain" },
    { "How's your father?": "Comment va ton père?" },
  ],
  [
    { "He's doing great": "Il va très bien" },
    { "Are you tired?": "Es-tu fatigué (fatiguée)?" },
    { "Yes, I am": "Oui, je le suis" },
    { "Are you hungry?": "As-tu faim?" },
    { "No, but I'm thirsty": "Non, mais j'ai soif" },
    { "Is your friend Chinese?": "Ton ami est-il Chinois?" },
    { "Yes, he is": "Oui, il l'est" },
    { "Are these your keys?": "Ce sont tes clés?" },
    { "Yes, they are [mine]": "Oui, ce sont les miennes" },
    { "That's my seat": "C'est mon siège" },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
  [
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
    { "key": "value" },
  ],
]